name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.WRITE_TOKEN }}
        submodules: 'true'
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build
      run: npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WRITE_TOKEN }}

    - name: Lint
      run: npm run lint

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.9
      with:
          ACCESS_TOKEN: ${{ secrets.WRITE_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist